language: node_js

cache:
  npm: true

node_js:
  - "10"

script:
  - git clone https://github.com/hexojs/hexo-theme-unit-test generate_test
  - git clone https://github.com/ikeq/hexo-theme-inside.git generate_test/themes/landscape
  - cd generate_test
  - npm install
  - hexo g & hexo g
  - cd ..
  - npm test
